<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
             <?php 
            
            $condition_i = $_product->getData('condition');
            $conditionTextArray = array(
                '6'=>"Fair",
                '5'=>"Good",
                '4'=>"Great",
                '3'=>"Excellent"
            );
             function getConditionRatingClass($index, $cindex) {
                $equalizedArray = array(
                    '6'=>1,
                    '5'=>2,
                    '4'=>3,
                    '3'=>4);
                if ($index <= $equalizedArray[$cindex]) {
                      return "starred";
                 }    
             }
                 ?>
             
             <div class="condition-rating">
             Condition:
             <span class="<?php echo getConditionRatingClass(1, $condition_i) ?>">☆</span><span class="<?php echo getConditionRatingClass(2, $condition_i) ?>">☆</span><span class="<?php echo getConditionRatingClass(3, $condition_i) ?>">☆</span><span class="<?php echo getConditionRatingClass(4, $condition_i) ?>">☆</span><span>(<?php echo $conditionTextArray[$condition_i]; ?>)</span>
             </div>
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <!-- <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?> -->
            <?php echo $this->getTierPriceHtml() ?>
            <?php// echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <!-- <?php if ($_product->isAvailable()): ?>
                <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In Stock') ?></span></p>
            <?php else: ?>
                <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of Stock') ?></span></p>
            <?php endif; ?>
            <p class="product-sku"><?php echo $this->__('Product Code:') ?> <span><?php echo $_product->getSku() ?></span></p>-->
            

            <div class="product-collateral akordeon">
                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description akordeon-item">
                        <div class="akordeon-item-head">
                            <div class="akordeon-item-head-container">
                                <div class="akordeon-heading">
                                    <?php echo $this->__('Description') ?>
                                </div>
                            </div>
                        </div>
                        <div class="akordeon-item-body">
                            <div class="akordeon-item-content">
                                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
      <!--   <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                <div class="box-collateral <?php echo "box-{$alias}"?> akordeon-item">
                    <?php if ($title = $this->getChildData($alias, 'title')):?>
                    <div class="akordeon-item-head">
                        <div class="akordeon-item-head-container">
                            <div class="akordeon-heading">
                                <?php echo $this->escapeHtml($title); ?>
                            </div>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php echo $html; ?>
                </div>
            <?php endforeach;?> -->
              <!--   <?php echo $this->getChildHtml('reviews') ?>
                <?php echo $this->getChildHtml('product_additional_data') ?>
                <?php echo $this->getChildHtml('upsell_products') ?> -->
            </div>
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>

                <?php if (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                        <?php if ($_product->getStockItem()->getIsInStock() == 0): ?>
                            <div class="add-to-cart">
                               <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart inactive" onclick="return false;"><span><span>Out of stock</span></span></button>
                           </div>
                        <?php endif; ?>
                    </div>
                <?php else://if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php endif; ?>
            </form>
        </div>

        <div class="clearer"></div>
    
            <div class="clear"></div>
            <script type="text/javascript">
        //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
             form.action = url;
         }
         var e = null;
//Start of our new ajax code
if(!url){
    url = jQuery('#product_addtocart_form').attr('action');
}
var data = jQuery('#product_addtocart_form').serialize();
data += '&isAjax=1';   
jQuery('#ajax_loader').show();
try {
    jQuery.ajax({
      url: url,
      dataType: 'json',
      type : 'post',
      data: data,
      success: function(data){
        jQuery('#ajax_loader').hide();
                                //alert(data.status + ": " + data.message);
                                if(jQuery('.mini-cart-layer')){
                                    jQuery('.mini-cart-layer').html(data.sidebar).click(function() {
                                        toggleTopCart();
                                    });
                                    var x = 0;
                                    var intervalID = setInterval(function () {

   // Your logic here
   jQuery(".mini-cart-layer").toggleClass("glow");

   if (++x === 4) {
     window.clearInterval(intervalID);
 }
}, 600);
                                }
                                // if(jQuery('.header .links')){
                                //     jQuery('.header .links').replaceWith(data.toplink);
                                // }
                            }
                        });
} catch (e) {
}
//End of our new ajax code
this.form.action = oldUrl;
if (e) {
    throw e;
}
}
}.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            
        //]]>
    </script>
</div>
<?php echo $this->getChildHtml('catalog.product.related') ?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.akordeon.product-collateral').akordeon({ buttons: true, toggle: true });
    });
</script>
</div>
