
<script type="text/javascript">// <![CDATA[
jQuery(function() {
  window.uploadedFilesCount = 0;
    jQuery('#file_upload').uploadify({
        'formData'     : {
          'timestamp' : '<?php echo $timestamp;?>',
          'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
        },
        'swf'      : '/skin/frontend/base/default/js/uploadify/uploadify.swf',
        'uploader' : '/skin/frontend/base/default/js/uploadify/uploadify.php',
        'onUploadSuccess': function(file) {
          jQuery("form.buy-sell").append('<input name="files[]" type="hidden" value="'+ file.name +'">');
          window.uploadedFilesCount++;
          jQuery("#uploaded-files-count span").text(window.uploadedFilesCount);
        },
         'onUploadStart' : function(file) {
            jQuery("form.buy-sell button[type=submit]").attr('disabled','disabled').attr("style",'background: #D8D8D8;font-size: 11px;border: none;text-shadow: none;box-shadow: none;').text("Processing...");
        },
        'onQueueComplete' : function(queueData) {
            jQuery("form.buy-sell button[type=submit]").removeAttr("disabled").removeAttr("style").text("Submit");
        },
        'onSWFReady': function() {
            jQuery("#file_upload-queue").after('<div id="uploaded-files-count"><span>0</span> files uploaded.</div>');
        },
        'fileTypeExts' : '*.gif; *.jpg; *.png; *.jpeg'
        // Put your options here
    });
});
// ]]></script>
