
<script type="text/javascript">// <![CDATA[
jQuery(function() {
    jQuery('#file_upload').uploadify({
        'formData'     : {
          'timestamp' : '<?php echo $timestamp;?>',
          'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
        },
        'swf'      : '/skin/frontend/base/default/js/uploadify/uploadify.swf',
        'uploader' : '/skin/frontend/base/default/js/uploadify/uploadify.php',
         'onUploadStart' : function(file) {
            jQuery(this).closest("form").find("button[type=submit]").attr('disabled','disabled').attr("style",'background: #D8D8D8;font-size: 11px;border: none;text-shadow: none;box-shadow: none;').text("Processing...");
        },
        'onQueueComplete' : function(queueData) {
            jQuery(this).closest("form").find("button[type=submit]").removeAttr("disabled").removeAttr("style").text("Submit");
        }
        // Put your options here
    });
});
// ]]></script>
