<style>
    .product-options { max-height: 150px; overflow: auto;}
</style>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php  echo $this->getAddToCartUrl($_product)//echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            
            <div class="product-shop">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>

                <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php // echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getTierPriceHtml() ?>
                <?php 
               
               $condition_i = $_product->getData('condition');
               $conditionTextArray = array(
                   '6'=>"Fair",
                   '5'=>"Good",
                   '4'=>"Great",
                   '3'=>"Excellent"
               );
                function getConditionRatingClass($index, $cindex) {
                   $equalizedArray = array(
                       '6'=>1,
                       '5'=>2,
                       '4'=>3,
                       '3'=>4);
                   if ($index <= $equalizedArray[$cindex]) {
                         return "starred";
                    }    
                }
                    ?>
                
                <div class="condition-rating">
                Condition:
                <span class="<?php echo getConditionRatingClass(1, $condition_i) ?>">☆</span><span class="<?php echo getConditionRatingClass(2, $condition_i) ?>">☆</span><span class="<?php echo getConditionRatingClass(3, $condition_i) ?>">☆</span><span class="<?php echo getConditionRatingClass(4, $condition_i) ?>">☆</span><span>(<?php echo $conditionTextArray[$condition_i]; ?>)</span>
                </div>
                <?php //echo $this->getChildHtml('extrahint') ?>
                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <h2><?php echo $this->__('Quick Overview') ?></h2>
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <!-- <span class="or"><?php echo $this->__('OR') ?></span> -->
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>

                

                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

            </div>

            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>
            
            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
        <script type="text/javascript">

            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                     form.action = url;
                 }
                 var e = null;
//Start of our new ajax code
if(!url){
    url = jQuery('#product_addtocart_form').attr('action');
}
var data = jQuery('#product_addtocart_form').serialize();
data += '&isAjax=1';   
jQuery('#ajax_loader').show();
try {
    jQuery.ajax({
      url: url,
      dataType: 'json',
      type : 'post',
      data: data,
      success: function(data){
        jQuery('#ajax_loader').hide();
                                //alert(data.status + ": " + data.message);
                                if(jQuery('.mini-cart-layer')){
                                    jQuery('.mini-cart-layer').html(data.sidebar).unbind("click").click(function() {
                                        toggleTopCart();
                                    });
                                    var x = 0;
                                    var intervalID = setInterval(function () {

   // Your logic here
   jQuery(".mini-cart-layer").toggleClass("glow");

   if (++x === 4) {
     window.clearInterval(intervalID);
 }
}, 600);
                                }
                                // if(jQuery('.header .links')){
                                //     jQuery('.header .links').replaceWith(data.toplink);
                                // }
                            }
                        });
} catch (e) {
}
//End of our new ajax code
this.form.action = oldUrl;
if (e) {
    throw e;
}
}
}.bind(productAddToCartForm);

productAddToCartForm.submitLight = function(button, url){
    if(this.validator) {
        var nv = Validation.methods;
        delete Validation.methods['required-entry'];
        delete Validation.methods['validate-one-required'];
        delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);

    </script>
 
        
        <!-- <div class="md-more-info" ><a href="<?php echo $_product->getProductUrl();?>"><span><?php echo $this->__('VIEW FULL PRODUCT DETAILS') ?></span></a></div> -->	
    </div>
</div>
